### ISSUE TITLE
Fodder with source not accepted by validation

### ISSUE THREAD

**Issue by fw2568** [eryph-org/dotnet-configmodel#66]
Fodder ref with source only 

``` yaml
 - source: gene:dbosoft/starter-food:win-starter
```

triggers

"The content or source must be specified when adding fodder."

This works:

``` yaml
 - source: gene:dbosoft/starter-food:win-starter
   content: 1234
```

However the rule should be that name requires content or source and that source can appear alone but never with content.

https://github.com/eryph-org/dotnet-configmodel/blob/2d9aab0d8079885482a535af4c52bdce2fee8b77/src/Eryph.ConfigModel.Catlets.Validation/CatletConfigValidations.cs#L75-L79

[AB#655](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/655)

**Comment by ChristopherMann** [comment]
The validation works correctly in version `0.3.0`. The issue was observed because the Eryph.ComputeClient Cmdlet was using an outdated version.
